In [5]:
#1
import numpy as np


In [2]:
#2
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
#3
a=np.arange(10, 100, 1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [16]:
#4
a[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [28]:
#5
a.reshape(3,30)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
#6
x = np.array([1,2,9,0,0,1,4,0])
print(x)
## cum aflu indicii? la ce se refera?

[1 2 9 0 0 1 4 0]


In [38]:
np.nonzero(x)##?????????????

(array([0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 2, 3, 4, 5, 6, 7], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [40]:
#7.
matr=np.identity(3)
print('3x3 matrix:')
print(matr)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
#7. Met 2
Z = np.eye(3)

print(Z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
#8
# np.random.uniform(low=-1, high=1, size=(50))
Z = np.random.uniform(-1,1,50)
print(Z)
m = Z.mean()
print(m)

[-0.83174432  0.67474919  0.78439389 -0.13928995  0.36376729 -0.11118947
 -0.87285977  0.91521278 -0.26563929 -0.03046233 -0.14237912 -0.49423215
 -0.75591392 -0.65557851  0.79222387 -0.77766034  0.10289582 -0.8867827
 -0.55862458  0.80828185  0.18008989  0.35677022  0.54321864  0.52242293
  0.063886   -0.44079534 -0.80558881 -0.99994816  0.62746281  0.09562077
  0.09306281 -0.70970797 -0.08964536  0.4956471   0.63596528  0.57002219
 -0.5254587   0.5381653  -0.85493253 -0.50486715  0.45388899  0.96521665
  0.69643009  0.7419356  -0.45585439 -0.81073821  0.75339769  0.88518228
  0.61271079  0.43795954]
0.03981374393603147


In [43]:
#9.
M = np.diag(1+np.arange(4),k=-1)

print(M)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [49]:
#10.
d=np.ones((5,3))
g=np.ones((3,2))
print(d)
print(g)
        
N = np.dot(d, g)

print(N)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [54]:
#11
d=np.ones((5,3))
g=np.ones((3,2))

N = np.dot(d, g)

print (N - N%1)

print (np.floor(N))


print (N.astype(int))

print (np.trunc(N))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [56]:
#12
V = np.random.random(10)

V.sort()

print(V)

[0.00366014 0.09131866 0.24533239 0.29800386 0.31190813 0.34708065
 0.35537939 0.41636949 0.61376167 0.89429693]


In [57]:
#13
Z = np.random.random((7,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)



[0.78717646 0.48253852 0.96142233 0.41514032 0.69143916 0.43437567
 1.14390985]
[0.91822841 0.73685449 1.06845811 1.24497677 0.68221381 0.80444454
 0.84067783]


In [10]:
#14.
M = np.random.randint(5,size=(10,10))
print(M)
n=M.flatten()
print(n)
v =np.random.randint(3)
print(v)

index = (np.abs(n-v)).argmin()

print(n[index])

[[3 4 2 4 4 1 4 0 0 4]
 [0 4 0 3 0 4 0 4 3 3]
 [1 2 0 3 4 0 3 1 0 3]
 [1 4 1 1 4 3 0 4 2 2]
 [1 4 0 0 4 1 0 0 2 1]
 [3 3 1 0 4 0 2 4 1 1]
 [3 3 1 3 3 4 1 1 3 2]
 [4 1 4 1 0 3 1 1 0 2]
 [0 0 0 4 2 4 4 3 1 4]
 [2 2 0 1 1 2 2 3 4 1]]
[3 4 2 4 4 1 4 0 0 4 0 4 0 3 0 4 0 4 3 3 1 2 0 3 4 0 3 1 0 3 1 4 1 1 4 3 0
 4 2 2 1 4 0 0 4 1 0 0 2 1 3 3 1 0 4 0 2 4 1 1 3 3 1 3 3 4 1 1 3 2 4 1 4 1
 0 3 1 1 0 2 0 0 0 4 2 4 4 3 1 4 2 2 0 1 1 2 2 3 4 1]
2
2
